### ISSUE TITLE
bug: fix course structured data

### ISSUE THREAD

**Issue by 3syth** [devsoc-unsw/unilectives#275]
Google has reported that the structured data for unilectives is invalid, specifically:

![Image](https://github.com/devsoc-unsw/unilectives/assets/48422312/3f88e219-df5b-41a1-8941-d5f8f4ad2962)

![Image](https://github.com/devsoc-unsw/unilectives/assets/48422312/1cee56a1-7c6f-40bf-9c58-9379936efbd8)

**Comment by eaglethrost** [comment]
![Screenshot 2024-05-11 at 18 40 15](https://github.com/devsoc-unsw/unilectives/assets/63914983/cf798ed7-c8f9-480a-b171-f16c969a74fb)
